### ISSUE TITLE
List of abbreviation is not printed

### ISSUE THREAD

**Issue by MormonJesus69420** [egraff/uit-thesis#66]
Hello!

I have problem with printing a list of abbreviations, I tried following what you have said to do in #65 but no list of abbreviations is shown. I even took and compiled the example you wrote, and nothing is shown, when I click on abbreviation in text it sends me back to top of the first page in document. I am running this on both linux and overleaf with same results.

**Comment by egraff** [comment]
What commands do you run when trying to compile your pdf?

Note that we do have a test (https://github.com/egraff/uit-thesis/blob/master/test/tests/test-acronyms%5B1%2C3%2C5-7%5D.tex) for use of the `glossaries` package, including the List of Abbreviations, so it's likely the problem is with your build setup or LaTeX file(s).

**Comment by MormonJesus69420** [comment]
On my Linux pc I am using TeX Live with compilation order pdflatex > bibtex >pdflatex > pdflatex. 
On overleaf compilation is done with TeX Live too and order is described here: https://www.overleaf.com/learn/how-to/How_does_Overleaf_compile_my_project%3F
In both cases I use the example file you provided in issue #65. It seems to be working when I try to compile it using Overleaf, but it won't compile properly on my PC. What is the right compilation order then?

**Comment by egraff** [comment]
You need to add an additional compilation step in the middle, where you run the `makeglossaries` command.

**Comment by MormonJesus69420** [comment]
Ah, righto, that worked, it might be smart to add that info to readme.
