### ISSUE TITLE
Errors related to languages

### ISSUE THREAD

**Issue by koen-vg** [egraff/uit-thesis#74]
Thanks for creating and maintaining this LaTeX template!

I ran into two errors which might be worth looking into:

1. During compilation, I get `Package hyphsubst Error: Unknown pattern usenglishmax.`. I managed to fix this temporarily by commenting out line 246 in `uit-thesis.cls`, namely `\RequirePackage[english=usenglishmax]{hyphsubst}`.

2. After that fix, I get `Package babel Error: You haven't defined the language norsk yet.`. The error then suggests that I might have misspelled the language, or not installed it. However, I have installed the `texlive-babel-norsk` package.

I'm using an up-to-date installation of Fedora 33, with a full installation of texlive (`texlive-scheme-full` on Fedora, to be specific). Am I just being stupid, or is there something to fix here? Let me know if I can provide any more information.

**Comment by egraff** [comment]
Hi,

I don't have any experience with Fedora distros (or installing/running TeX Live on Fedora) - however, I do have prior experience with some pitfalls w.r.t TeX Live on Ubuntu, which may be analogous to your problem.

Both of those errors suggest to me that the TeX Live install isn't a complete install (even if the package is called `texlive-scheme-full`). Given that package name, I'm guessing that you installed TeX Live using Fedora's package manager (analogous to apt on Ubuntu?), rather than using the official `tl-install` script? On Ubuntu, at least, all the apt packages lock down specific versions of the LaTeX packages (which I guess is the idea), and provide a TeX Live installation without `tlmgr`, so you have no way of updating or managing your packages besides apt. My experience with using apt to install TeX Live is an unpleasant one, and I've found that at least in the past it has been practically impossible to get a complete install this way, and the packages have been quite out-of-date.

I suggest that you check if you have `tlmgr` on your system, and if not, uninstall TeX Live via your package manager, and re-install it the "official" way. If you want a "stable" release, you can go for TeX Live 2019, which is the oldest version of TeX Live that is currently supported by the uit-thesis template (I tried to support older versions in the past, but at some point some quite intrusive non-backwards-compatible changes were introduces in some of the LaTeX packages that made this very hard).

I'd be quite surprised if this doesn't work, since I have regression tests that install TeX Live 2019 (on Ubuntu), and compile various documents using the uit-thesis template 😉 I can't imagine it would behave much differently, if TeX Live is installed the same way on Fedora.

**Comment by koen-van-greevenbroek** [comment]
Hey,

Thanks for the reply!

The Fedora texlive packages are supposed to be quite up-to-date, but I guess they may have some errors in how exactly they are packaging them.

So I removed every texlive package I had installed with dnf, and installed the upstream 2020 version directly using `tl-install`.

This time I got another error... 
```
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/xcharter/XCharter.sty
`XCharter' v1.208, 2020/09/20 Text macros for XCharter, an extension of Charter
 (msharpe)
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/base/fontenc.sty
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/cyrillic/t2aenc.def
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/base/t2aenc.dfu))
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/ly1/ly1enc.def
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/base/ly1enc.dfu)))
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/carlisle/scalefnt.sty))
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/xcharter/T1XCharter-TLF.fd
)
(/home/koen/.local/texlive/2020/texmf-dist/tex/latex/xcharter/T1XCharter-TOsF.f
d)
kpathsea: Running mktextfm XCharter1-Roman-tosf-t1
/home/koen/.local/texlive/2020/texmf-dist/web2c/mktexnam: Could not map source abbreviation X for XCharter1-Roman-tosf-t1.
/home/koen/.local/texlive/2020/texmf-dist/web2c/mktexnam: Need to update /home/koen/.local/texlive/2020/texmf-dist/fonts/map/fontname/special.map?
mktextfm: Running mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input XCharter1-Roman-tosf-t1
This is METAFONT, Version 2.7182818 (TeX Live 2020) (preloaded base=mf)


kpathsea: Running mktexmf XCharter1-Roman-tosf-t1
! I can't find file `XCharter1-Roman-tosf-t1'.
<*> ... nonstopmode; input XCharter1-Roman-tosf-t1
                                                  
Please type another input file name
! Emergency stop.
<*> ... nonstopmode; input XCharter1-Roman-tosf-t1
                                                  
Transcript written on mfput.log.
grep: XCharter1-Roman-tosf-t1.log: Ingen slik fil eller filkatalog
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; ; nonstopmode; input XCharter1-Roman-tosf-t1' failed to make XCharter1-Roman-tosf-t1.tfm.
kpathsea: Appending font creation commands to missfont.log.

! Font T1/XCharter-TOsF/m/n/10.95=XCharter1-Roman-tosf-t1 at 10.73094pt not loa
dable: Metric (TFM) file not found.
<to be read again> 
                   relax 
l.668 \osfstyle
```
I definitely have the `xcharter` package installed though, I installed the full scheme.

This is the error I get when trying to compile the example provided by the `uit-thesis` package (which needs a `print` or `noprint` document class option by the way). I have run `texhash` of course, and whatever other "refresh" command I could find for texlive.

I'm by no means a texlive expert. Maybe I'm missing something stupid, or somehow something from the Fedora installation has messed up the "official" installation?

I will look at it some more tomorrow, but if you have some ideas, I'm all ears :)

**Comment by egraff** [comment]
Yes, you are quite right! I only noticed this problem after I wrote back to you yesterday (I have neglected to pay attention to my CI for some time now). I have, however, already triaged the problem, and found that it is the XCharter package that has been broken since CTAN revision 56918, which was uploaded on Nov 12. I have already notified the package maintainer, and am hoping for a fix to appear as soon as possible 🙂 (there is little I can do in the meantime).

If you want to "hack around" the problem, you can find the line where XCharter is included in your installed cls file:
https://github.com/egraff/uit-thesis/blob/b861b8379d1a9eed052263410dcb7a14f9f8cdde/texmf-tds/tex/latex/uit-thesis/uit-thesis.cls#L656
and add the package option `osfI`. This will mean that the digit 1 will be rendered differently, so you should remember to go back and remove that option (or reinstall the template to overwrite) after a proper fix of the XCharter package is in place.

However, I've noticed that there's even another regression I need to fix, where it seems the `\printacronyms` command is no longer available, and I haven't started looking at this yet. So another option, if you'd like to get something working right away, is to install TeX Live 2019 instead of the most up-to-date but "unstable" TeX Live 2020 😉

(Requiring a `print` or `noprint` option is done deliberately, to force the author to make a conscious decision about what type of pdf to produce).

**Comment by koen-van-greevenbroek** [comment]
Okay, no problem. I'm not in a rush, but I have installed and switched to TeX Live 2019, and now everything works. I'll just update the 2020 version and switch back to it whenever the different issues get sorted out :)

Thanks again for the help!
