### ISSUE TITLE
LaTeX Error: Command `\Bbbk' already defined.

### ISSUE THREAD

**Issue by pguio** [egraff/uit-thesis#80]
Hi there,

I believe it is possible to avoid the redefinition error of \Bbbk by replacing
\usepackage{amsmath}
with
\usepackage{amsmath,amssymb}

Many thanks,
Patrick

**Comment by egraff** [comment]
Why do you try to use `amssymb`?
I think the answer you're looking for is this: https://tex.stackexchange.com/a/564079/73383.

**Comment by egraff** [comment]
To be clear, what I suggest is not to import `amssymb` (I'm assuming you have a `\usepackage{amssymb}` somewhere in your preamble?)

**Comment by pguio** [comment]
Indeed and it was as quoted in in my first email

**Comment by pguio** [comment]
Yes that was the patch suggestion, my master student do not have amssymb 
in his document but I found out adding amssymb in uit-thesis.cls fixes 
the redefinition of \Bbbk and as a rule of thumb I always tries to avoid 
error and warnings :-)

**Comment by egraff** [comment]
> my master student do not have amssymb in his document but I found out adding amssymb in uit-thesis.cls fixes the redefinition of \Bbbk

IMHO that doesn't make much sense - something is trying to redefine `\Bbbk`, and I'd think that something is most likely to be `amssymb`. If they don't include `amssymb` directly, could it be there is a package that imports it transitively? The pdflatex logs should give an indication of where in the document the error occurs, and that should make it possible to figure out which package the error comes from.

Or, if you'd like to try out something for debugging this, you could try to put this as the very first thing in the preamble (i.e. right after the `\documentclass` declaration):

```tex
\makeatletter
\ult@disallowpackage[DEBUG]{amssymb}
\makeatother
```

that should stall the compilation at the point where `amssymb` is imported, _if_ it is imported.

> as a rule of thumb I always tries to avoid error and warnings :-)

That is a good rule of thumb, but I don't think the suggested fix is the right one - IMHO it's analogous to removing the symptoms instead of the root cause.

**Comment by pguio** [comment]
Oops sorry, my mistake! You are completely correct, amssymb was loaded 
from another style file.
Thank you again for your prompt reply

**Comment by egraff** [comment]
Out of curiosity, which other package was it that loaded amssymb?

**Comment by pguio** [comment]
It was actually one of my package for vectorial operators which I have 
now updated as it didn't make sense to require amssymb there.
Thank you
