### ISSUE TITLE
Latex error on Fedora 36 with texlive 20210325

### ISSUE THREAD

**Issue by pguio** [egraff/uit-thesis#81]
Hi there,
I am trying to compile my master student's thesis on my linux box with fedora 36 using rubber and I got into some troubles

* /usr/share/texlive/texmf-dist/tex/generic/oberdiek/hyphsubst.sty:227: Package hyphsubst Error: Unknown pattern `usenglishmax'

I am not able to find this pattern file, is it standard? There does not seem to be many hits when googling for texlive usenglishmax. I currently have most of the rpm for english hyphenations
texlive-hyphen-base-svn58630-57.fc36.noarch
texlive-hyph-utf8-svn58619-57.fc36.noarch
texlive-hyphen-english-svn58609-57.fc36.noarch
texlive-hyphenex-svn57387-57.fc36.noarch
texlive-dehyph-svn48599-57.fc36.noarch

That would be great to have a UK english alternative too!

* uit-thesis.cls:2467: Package babel Error: You haven't defined the language norsk yet.

It looks like this babel error can be fixed by adding norsk in the class options prior to english
\documentclass[noprint,norsk,USenglish]{uit-thesis}

* Finally when runninng rubber without glossaries I get 
$ rubber --pdf main
Rubber directive 'onchange' is valid only in unsafe mode
[biblio] cannot find bibliography style plainnat
[leaf] 'main.glo' does not exist

that can be fixed by creating an empty main.glo (touch main.glo)

I hope that helps

Regards,

Patrick

**Comment by egraff** [comment]
For the first part, I'd _really_ advise against installing TeX Live from a package manager. If possible, use the official install-tl script instead. However, if you _have_ to use the package manager, make sure you install a complete TeX Live distro (i.e. texlive-scheme-full).

> That would be great to have a UK english alternative too!
Yes, but that would be a separate feature request - the template currently only supports US English.

> that can be fixed by creating an empty main.glo
I do not have any experience with rubber, but this sounds like a hack, so there must be a better solution. This problem does not occur with regular pdflatex or latexmk. However, I'd start with making sure you have a complete TeX Live distro first.

**Comment by pguio** [comment]
Thank you for your prompt reply.
I think installing a full texlive distro in order to be able to compile 
a master thesis is a bit of an overkill, isn't it? I have used latex for 
  research and teaching since the mid 90's with redhat/fedora and I 
never had an issue with a missing file but thank you for the suggestion.

Shall I submit a separate feature request for the UK english option?

**Comment by egraff** [comment]
> I have used latex for research and teaching since the mid 90's with redhat/fedora and I never had an issue with a missing file but thank you for the suggestion.

Well, all I can say to that is that we've had different experiences, then 😛 I had a lot of problems with installing LaTeX packages (or more precisely, with figuring out which dpkg packages corresponded to which missing TeX Live packages) on Ubuntu/Debian-based systems in the early 2010s. For me, that was a nightmare that I'm never going back to 😆

> I think installing a full texlive distro in order to be able to compile a master thesis is a bit of an overkill, isn't it?

Well, yes, but then you avoid the guesswork of which packages to install 😉 If you look at https://github.com/egraff/ult-base/blob/b09b7c3a214387da5b7df25f0a094dee942cb501/ci/texlive2023.profile, you can see that I don't actually install scheme-full when running tests in my CI, but I still keep it at the less granular "collection"-level (as opposed to picking out individual packages) when selecting what to install.

> Shall I submit a separate feature request for the UK english option?

Please raise a separate GitHub issue for it 🙂 unfortunately, I can't make any promises as to whether I'll have time to look at this soon-ish, since I have to use my spare time for anything related to this template (and the amount of work for just keeping it "alive" has been a lot lately).

**Comment by pguio** [comment]
Thanks that's useful. I just noticed the
collection-langenglish
that might help but I don't want to have to install all doc packages...

**Comment by pguio** [comment]
I had a more careful look at the issue with the US hyphenation pattern 
usenglishmax. It looks like it is included in the english hyphenation / 
babel distro and is the default pattern file loaded but it is called 
USenglish instead of usenglishmax.

-\RequirePackage[english=usenglishmax]{hyphsubst}
+\RequirePackage[english=USenglish]{hyphsubst}

Patrick

**Comment by egraff** [comment]
No, "usenglishmax" is deliberate. You're probably just missing the package that contains those patterns.
